name: plantapp_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-288.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plant_img_2.png
    - assets/bg_img_1.webp
    - assets/listView_plant.png
